# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c10bd61a912c2ef808362786ca3fa8bbf832891b77f866dddfc18bee8a67c30de8ce4226e69d312c1d20ce708d47c5161bc5fada414ac0f416eac886f1941db1

test:
  secret_key_base: 66fb8980f4c54ffb8a34fb7c6a6937bc0bb2216ef6f834410a27df3290422ee9e0623f1f5cfed23c58a53e4332153c2760cf86df1536d0b05ce301cd0dc86f57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
